<template>
  <div class="fixed inset-0 z-[60] overflow-y-auto bg-[#f6f8f7] p-4 dark:bg-dark-950 sm:p-6">
    <div class="mx-auto max-w-[1800px]"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-xl font-semibold">{{ t('admin.accounts.pelicanTest.history') }}</h2><p class="text-sm text-gray-500">{{ t('admin.accounts.pelicanTest.dashboardHint') }}</p></div><button class="btn btn-secondary" @click="$emit('close')">{{ t('common.close') }}</button></div>
      <div v-if="loading" class="py-20 text-center text-sm text-gray-500">{{ t('common.loading') }}...</div>
      <div v-else-if="cards.length" class="grid grid-cols-1 gap-4 lg:grid-cols-2 2xl:grid-cols-4"><article v-for="card in cards" :key="card.account.id" class="cursor-pointer overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:border-primary-300 hover:shadow-md dark:border-dark-700 dark:bg-dark-800" @click="selected = card.result"><div class="p-4"><h3 class="font-semibold">{{ card.account.name }}</h3><p class="text-xs text-gray-500">#{{ card.account.id }} · {{ card.manual ? t('admin.accounts.pelicanTest.sourceManual') : t('admin.accounts.pelicanTest.sourceScheduled') }}</p><div class="mt-3 space-y-1 text-xs text-gray-500"><div>{{ card.manual ? `${card.manual.modelId} / ${card.manual.reasoningEffort}` : `${card.result?.pelican_config?.model_id} / ${card.result?.pelican_config?.reasoning_effort}` }} · {{ t('admin.accounts.pelicanTest.duration') }} {{ card.manual ? `${((card.manual.durationMs || 0) / 1000).toFixed(1)} s` : `${((card.result?.latency_ms || 0) / 1000).toFixed(1)} s` }}</div><div>{{ t('admin.accounts.pelicanTest.generatedAt') }}：{{ card.manual ? formatDate(card.manual.startedAt || new Date().toISOString()) : formatDate(card.result!.started_at) }}</div></div><div class="mt-3 aspect-[4/3] overflow-hidden rounded-xl bg-white"><iframe :srcdoc="extractHtml(card.manual ? card.manual.html || card.manual.output : card.result!.response_text)" class="h-full w-full border-0" sandbox="allow-scripts" referrerpolicy="no-referrer" /></div></div><div class="border-t px-4 py-3 text-sm text-primary-600">{{ t('admin.accounts.pelicanTest.preview') }}</div></article></div>
      <div v-else class="rounded-xl border border-dashed border-gray-300 bg-white py-20 text-center text-sm text-gray-500">{{ t('admin.accounts.pelicanTest.noHistory') }}</div>
    </div>
    <div v-if="selected" class="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4" @click.self="selected = null"><div class="flex h-full w-full max-w-6xl flex-col overflow-hidden rounded-xl bg-white"><div class="flex items-center justify-between border-b px-4 py-3"><span class="text-sm font-medium">{{ selected.pelican_config?.model_id }} / {{ selected.pelican_config?.reasoning_effort }} · {{ (selected.latency_ms / 1000).toFixed(1) }} s</span><button class="btn btn-secondary" @click="selected = null">{{ t('common.close') }}</button></div><iframe :srcdoc="extractHtml(selected.response_text)" class="min-h-0 flex-1 w-full border-0" sandbox="allow-scripts" referrerpolicy="no-referrer" /></div></div>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { scheduledTestsAPI } from '@/api/admin/scheduledTests'
import type { Account, AccountListItem, ScheduledTestPlan, ScheduledTestResult } from '@/types'
const props = defineProps<{ accounts: AccountListItem[]; account: Account | null; manualRecord: { createdAt: string; modelId: string; reasoningEffort: string; runs: Array<{ html: string; output: string; durationMs?: number; startedAt?: string }> } | null }>(); defineEmits<{ close: [] }>(); const { t } = useI18n(); const loading = ref(true); const selected = ref<ScheduledTestResult | null>(null)
const cards = ref<Array<{ account: AccountListItem | Account; plan: ScheduledTestPlan | null; result: ScheduledTestResult | null; manual?: { html: string; output: string; durationMs?: number; startedAt?: string; modelId: string; reasoningEffort: string } }>>([])
function formatDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'short', timeStyle: 'medium' }).format(new Date(value)) }
function extractHtml(raw: string) { let html = raw.trim(); const start = html.search(/<!doctype html|<html|<svg/i); if (start >= 0) html = html.slice(start); if (/<svg[\s>]/i.test(html) && !/<html[\s>]/i.test(html)) html = `<!doctype html><html><body>${html}</body></html>`; return html }
onMounted(async () => { const source = [...props.accounts]
 if (props.account && !source.some(item => item.id === props.account!.id)) source.push(props.account as unknown as AccountListItem)
 const loaded = await Promise.all(source.map(async account => { const plans = await scheduledTestsAPI.listByAccount(account.id); const plan = plans.find(item => item.pelican_config) || null; const results = plan ? await scheduledTestsAPI.listResults(plan.id, 1, true) : []; return plan && results[0] ? { account, plan, result: results[0], manual: undefined } : null }))
 const manual = props.manualRecord && props.account ? { account: props.account, plan: null, result: null, manual: { ...props.manualRecord.runs[0], modelId: props.manualRecord.modelId, reasoningEffort: props.manualRecord.reasoningEffort } } : null
 cards.value = [...loaded.filter(Boolean), ...(manual ? [manual] : [])] as typeof cards.value
 loading.value = false })
</script>
